package ru.practicum.kanban.servers.handlers;

public enum EndPoint {

    GET_TASKS,
    GET_TASK_BY_ID,
    CREATE_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    GET_SUBTASKS_BY_EPIC_ID,
    CREATE_SUBTASK,
    UPDATE_SUBTASK,
    DELETE_SUBTASK,
    GET_EPICS,
    GET_EPIC_BY_ID,
    CREATE_EPIC,
    UPDATE_EPIC,
    DELETE_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED_TASK,
    UNKNOWN

}
